version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: social-media
      POSTGRES_USER: social-media
      POSTGRES_PASSWORD: social-media

